### ISSUE TITLE
Data itself

### ISSUE THREAD

**Issue by awmeade** [izk8/2018_SIOP_Machine_Learning_Winners#1]
Isaac, Do you have permission to post the data itself or know if it's publically available somewhere? Great job! Adam

**Comment by izk8** [comment]
Sadly, they are not releasing the dataset to the public. One of the major drawbacks of the competition IMO. I will reach out to Dan to double check.

**Comment by DrDRHawthorne** [comment]
Isaac, will the materials still be released about how to learn more about Machine Learning in general? I'm really interested in getting up to speed on the techniques. Thanks!

**Comment by izk8** [comment]
@DrDRHawthorne Is there a particular type of ML that you are interested in? Maybe we can share some cool resources. On the other hand, I have updated the repo with all the code from the winning submissions!

**Comment by DrDRHawthorne** [comment]
I saw that. Actually, I'll have to get back to you on the type I'm interested in. Since, while I was poking around on here and found a nice thread with a lot of summary materials, and I'm currently working through this book (http://www.deeplearningbook.org/contents/intro.html). There's a lot of good summary information and history there.

**Comment by izk8** [comment]
@DrDRHawthorne Awesome! The Goodfellow et al (2016) deep learning book is where I got the definition for AI vs ML vs DL used in 4 presentations at SIOP this year and many client convos.  That intro chapter is very nice.
